In [1]:
import pandas as pd

In [2]:
list_feedback=[]
list_target=[]
with open('data/en-training.txt') as dev:
    for i in dev:
        feedback=i.strip().lower().split()
        if len(feedback) >= 1:
            target=feedback[-1]
            del(feedback[0])
            del(feedback[-1])
            list_feedback.append(feedback)
            list_target.append(target)

In [3]:
list_feedback

[['the',
  'give',
  'me',
  'a',
  'room',
  'which',
  'was',
  'so',
  'smelly',
  'and',
  'the',
  'floor',
  'was',
  'wet,',
  'then',
  'they',
  'change',
  'me',
  'to',
  'another',
  'room',
  'which',
  'the',
  'power',
  'is',
  'not',
  'working',
  'the',
  'room,',
  'and',
  'had',
  'to',
  'wait',
  '40',
  'mins',
  'to',
  'change',
  'me',
  'to',
  'another',
  'room',
  'for',
  'the',
  'third',
  'time.'],
 ['unfortunately',
  'there',
  'was',
  'a',
  'mix',
  'up',
  'with',
  'my',
  'passport',
  'and',
  'visa,',
  'and',
  'i',
  "couldn't",
  'get',
  'through',
  'customs',
  'at',
  'charles',
  'de',
  'gaulle.'],
 ['the',
  '(basic)',
  'room',
  'was',
  'comfortable',
  'and',
  'not',
  'too',
  'small.'],
 ['our',
  'primary',
  'concierge,',
  '[name[,',
  'was',
  'amazing',
  'in',
  'his',
  'attitude',
  'of',
  'caring',
  'and',
  'willingness',
  'to',
  'help.'],
 ['we',
  'booked',
  'through',
  'priceline',
  '(paying',
  'more',


In [4]:
list_target

['complaint',
 'meaningless',
 'comment',
 'comment',
 'complaint',
 'comment',
 'comment',
 'meaningless',
 'complaint',
 'comment',
 'complaint',
 'comment',
 'comment',
 'meaningless',
 'comment',
 'comment',
 'request',
 'complaint',
 'complaint',
 'comment',
 'comment',
 'comment',
 'comment',
 'complaint',
 'meaningless',
 'complaint',
 'complaint',
 'complaint',
 'comment',
 'comment',
 'complaint',
 'comment',
 'comment',
 'complaint',
 'comment',
 'comment',
 'comment',
 'meaningless',
 'complaint',
 'comment',
 'complaint',
 'meaningless',
 'complaint',
 'complaint',
 'comment',
 'meaningless',
 'complaint',
 'complaint',
 'complaint',
 'comment',
 'complaint',
 'comment',
 'complaint',
 'comment',
 'comment',
 'complaint',
 'comment',
 'comment',
 'complaint',
 'comment',
 'meaningless',
 'comment',
 'comment',
 'complaint',
 'complaint',
 'meaningless',
 'complaint',
 'comment',
 'complaint',
 'comment',
 'undefined',
 'comment',
 'complaint',
 'comment',
 'comment',
 'comm

In [5]:
stopwords=[]
with open('data/stopwords.txt') as stops:
    for i in stops:
        stopwords.append(i.strip())
stopwords

['a',
 'about',
 'above',
 'across',
 'after',
 'afterwards',
 'again',
 'against',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'another',
 'any',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'are',
 'around',
 'as',
 'at',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'bill',
 'both',
 'bottom',
 'but',
 'by',
 'call',
 'can',
 'cannot',
 'cant',
 'co',
 'computer',
 'con',
 'could',
 'couldnt',
 'cry',
 'de',
 'describe',
 'detail',
 'do',
 'done',
 'down',
 'due',
 'during',
 'each',
 'eg',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'etc',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'few',
 'fifteen',
 'fify',
 'fill',
 'find',
 'fire',
 'first',
 'f

In [6]:
fdbk=[]
for i in list_feedback:
    refined_fd=[]
    for j in i:
        if j not in stopwords:
            refined_fd.append(j)
    fdbk.append(refined_fd)
fdbk

[['room',
  'smelly',
  'floor',
  'wet,',
  'change',
  'room',
  'power',
  'working',
  'room,',
  'wait',
  '40',
  'mins',
  'change',
  'room',
  'time.'],
 ['unfortunately',
  'mix',
  'passport',
  'visa,',
  "couldn't",
  'customs',
  'charles',
  'gaulle.'],
 ['(basic)', 'room', 'comfortable', 'small.'],
 ['primary',
  'concierge,',
  '[name[,',
  'amazing',
  'attitude',
  'caring',
  'willingness',
  'help.'],
 ['booked',
  'priceline',
  '(paying',
  'listed',
  'price',
  'hotel',
  'website).',
  'desk',
  'arrived',
  '10',
  'minutes.'],
 ['fairly', 'easy,', 'definitely', 'stuck.'],
 ['perfect', 'stay', 'little', 'boutique', 'hotel.'],
 ['previous', 'comment.'],
 ['contact', 'details', 'gone.'],
 ['great', 'tool,'],
 ['present', 'providing', 'snacks', 'evening', 'time.'],
 ['room,', 'amenities,', 'service,', 'staff', 'spa', 'wonderful'],
 ['make',
  'life',
  'easier',
  'worth',
  'good',
  'rating,',
  "don't",
  'leave',
  'instructional',
  'videos',
  'line',
  'w

In [7]:
len(list_target),len(list_feedback)

(3065, 3065)

In [8]:
from collections import defaultdict
d=defaultdict(int)
refnd_fdb=[]
for i in fdbk:
    for j in i:
        d[j]+=1
for i in fdbk:
    temp_fd=[]
    for j in i:
        if d[j]>1:
            temp_fd.append(j)
    refnd_fdb.append(temp_fd)
refnd_fdb

[['room',
  'floor',
  'change',
  'room',
  'power',
  'working',
  'room,',
  'wait',
  '40',
  'mins',
  'change',
  'room',
  'time.'],
 ['unfortunately', 'mix', "couldn't"],
 ['room', 'comfortable', 'small.'],
 ['primary', 'amazing', 'attitude', 'caring', 'help.'],
 ['booked', 'listed', 'price', 'hotel', 'desk', 'arrived', '10', 'minutes.'],
 ['fairly', 'definitely'],
 ['perfect', 'stay', 'little', 'boutique', 'hotel.'],
 ['previous', 'comment.'],
 ['contact', 'details', 'gone.'],
 ['great', 'tool,'],
 ['providing', 'snacks', 'evening', 'time.'],
 ['room,', 'service,', 'staff', 'spa', 'wonderful'],
 ['make',
  'life',
  'easier',
  'worth',
  'good',
  'rating,',
  "don't",
  'leave',
  'videos',
  'line',
  'watch'],
 ['like', 'problem', 'kind', 'hotel', 'self', 'did', 'make', 'right'],
 ['pool', 'amazing.'],
 ['best', 'player', 'before.'],
 ['want', 'winsetup', 'usb', 'work', 'win8'],
 ['quite', 'bad', 'impression'],
 ['search', "doesn't", 'resume'],
 ['imperial', 'hotel', 'feat

In [9]:
count=0
for i in refnd_fdb:
    if len(i)==0:
        refnd_fdb.remove(i)
        list_target.pop(count)
    count+=1
refnd_fdb

[['room',
  'floor',
  'change',
  'room',
  'power',
  'working',
  'room,',
  'wait',
  '40',
  'mins',
  'change',
  'room',
  'time.'],
 ['unfortunately', 'mix', "couldn't"],
 ['room', 'comfortable', 'small.'],
 ['primary', 'amazing', 'attitude', 'caring', 'help.'],
 ['booked', 'listed', 'price', 'hotel', 'desk', 'arrived', '10', 'minutes.'],
 ['fairly', 'definitely'],
 ['perfect', 'stay', 'little', 'boutique', 'hotel.'],
 ['previous', 'comment.'],
 ['contact', 'details', 'gone.'],
 ['great', 'tool,'],
 ['providing', 'snacks', 'evening', 'time.'],
 ['room,', 'service,', 'staff', 'spa', 'wonderful'],
 ['make',
  'life',
  'easier',
  'worth',
  'good',
  'rating,',
  "don't",
  'leave',
  'videos',
  'line',
  'watch'],
 ['like', 'problem', 'kind', 'hotel', 'self', 'did', 'make', 'right'],
 ['pool', 'amazing.'],
 ['best', 'player', 'before.'],
 ['want', 'winsetup', 'usb', 'work', 'win8'],
 ['quite', 'bad', 'impression'],
 ['search', "doesn't", 'resume'],
 ['imperial', 'hotel', 'feat

In [10]:
len(list_target),len(refnd_fdb)

(2952, 2952)

In [11]:
import gensim
d2=gensim.corpora.Dictionary(refnd_fdb)
bow_list=[]
for i in refnd_fdb:
    bow_list.append(d2.doc2bow(i))
bow_list

C:\Users\vandana\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


[[(0, 1),
  (1, 2),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 3),
  (6, 1),
  (7, 1),
  (8, 1),
  (9, 1)],
 [(10, 1), (11, 1), (12, 1)],
 [(5, 1), (13, 1), (14, 1)],
 [(15, 1), (16, 1), (17, 1), (18, 1), (19, 1)],
 [(20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1)],
 [(28, 1), (29, 1)],
 [(30, 1), (31, 1), (32, 1), (33, 1), (34, 1)],
 [(35, 1), (36, 1)],
 [(37, 1), (38, 1), (39, 1)],
 [(40, 1), (41, 1)],
 [(7, 1), (42, 1), (43, 1), (44, 1)],
 [(6, 1), (45, 1), (46, 1), (47, 1), (48, 1)],
 [(49, 1),
  (50, 1),
  (51, 1),
  (52, 1),
  (53, 1),
  (54, 1),
  (55, 1),
  (56, 1),
  (57, 1),
  (58, 1),
  (59, 1)],
 [(24, 1), (55, 1), (60, 1), (61, 1), (62, 1), (63, 1), (64, 1), (65, 1)],
 [(66, 1), (67, 1)],
 [(68, 1), (69, 1), (70, 1)],
 [(71, 1), (72, 1), (73, 1), (74, 1), (75, 1)],
 [(76, 1), (77, 1), (78, 1)],
 [(79, 1), (80, 1), (81, 1)],
 [(24, 1), (82, 1), (83, 1), (84, 1), (85, 1)],
 [(24, 1), (32, 1), (51, 1), (86, 1), (87, 1), (88, 1), (89, 1)],
 [(90, 1)],
 [(51, 1)

In [12]:
cnt=len(d2)
cnt
dense_bow=gensim.matutils.corpus2dense(bow_list,num_terms=cnt).transpose()
dense_bow

C:\Users\vandana\Anaconda3\lib\site-packages\gensim\matutils.py:491: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  result = np.column_stack(sparse2full(doc, num_terms) for doc in corpus)


array([[1., 2., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [13]:
list_target
refnd_trg=[]
for i in list_target:
    if i=='comment':
        refnd_trg.append(0)
    elif i=='complaint':
        refnd_trg.append(1)
    elif i=='meaningless':
        refnd_trg.append(2)
    elif i=='request':
        refnd_trg.append(3)
    elif i=='bug':
        refnd_trg.append(4)
    else:
        refnd_trg.append(5)
refnd_trg        

[1,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 3,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 5,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 4,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 4,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 4,
 0,
 0,
 0,
 3,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 5,
 0,
 4,
 2,
 0,
 4,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 1,
 3,
 1,
 2,
 3,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 3,
 1,
 0,
 0,
 2,
 3,
 4,
 0,
 2,
 3,
 0,
 0,
 0,
 1,
 1,
 3,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 4,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 2,


In [14]:
len(refnd_trg)

2952

In [15]:
tfidf=gensim.models.TfidfModel(bow_list)
tfidf

In [16]:
tfidf_list=tfidf[bow_list]
tfidf

In [17]:
dense_tfidf=gensim.matutils.corpus2dense(tfidf_list,num_terms=count).transpose()
dense_tfidf

array([[0.31545243, 0.48988238, 0.25199717, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [18]:
import sklearn
from sklearn.model_selection import KFold
kf=KFold(n_splits=10,shuffle=True)
dataset=dense_tfidf
sd=list(kf.split(dataset))
sd

[(array([   0,    1,    2, ..., 2949, 2950, 2951]),
  array([   4,   11,   29,   42,   51,   55,   60,   62,   64,   76,   82,
           84,   88,   95,  114,  120,  151,  154,  179,  180,  183,  187,
          188,  196,  210,  215,  217,  232,  238,  265,  272,  275,  280,
          283,  285,  290,  291,  305,  308,  322,  333,  344,  347,  350,
          355,  363,  365,  375,  377,  396,  404,  414,  419,  433,  458,
          475,  483,  487,  491,  492,  512,  513,  537,  538,  555,  562,
          566,  575,  611,  616,  620,  636,  648,  686,  688,  689,  708,
          720,  721,  726,  728,  742,  778,  793,  802,  804,  809,  818,
          840,  859,  889,  903,  940,  949,  961,  969,  981,  992,  997,
          999, 1000, 1009, 1015, 1017, 1019, 1024, 1030, 1035, 1037, 1038,
         1045, 1056, 1064, 1097, 1106, 1124, 1145, 1154, 1161, 1185, 1196,
         1199, 1201, 1202, 1226, 1234, 1236, 1263, 1264, 1265, 1283, 1307,
         1326, 1335, 1338, 1364, 1366, 1380, 140

In [19]:
import numpy as np
from sklearn import svm
#from sklearn.naive_bayes import GaussianNB
#from sklearn.naive_bayes import BernoulliNB
#from sklearn.naive_bayes import MultinomialNB
#from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
#from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
acc_list=[]
f1_scores = []
precision_scores=[]
recall_scores=[]
for test,train in sd:
    train_data=[]
    train_label=[]
    test_data=[]
    test_label=[]
    for i in train:
        train_data.append(dataset[i])
        train_label.append(refnd_trg[i])
    for j in test:
        test_data.append(dataset[j])
        test_label.append(refnd_trg[j])
    classifier=svm.SVC()
    #classifier=GaussianNB()
    #classifier=BernoulliNB()
    #classifier=MultinomialNB()
    #classifier=KNeighborsClassifier(n_neighbors=10)
    
    classifier = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
    classifier = classifier.fit(train_data, train_label)
    predict=classifier.predict(test_data)
#     print(type(test_label),type())
    incorrect=(predict!=test_label).sum()
    score = f1_score(test_label, predict, average='weighted')
    score1 = precision_score(test_label, predict, average='weighted')
    score2 = recall_score(test_label, predict, average='weighted')
#     print(score)
    f1_scores.append(score)
    precision_scores.append(score1)
    recall_scores.append(score2)
    acc=(len(test_label)-incorrect)/len(test_label)
    acc_list.append(acc)

C:\Users\vandana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\vandana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\vandana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\vandana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\vandana\Anaconda3\lib\site-packages\skl

In [20]:
np.array(acc_list).max()

0.5534638554216867

In [21]:
np.array(f1_scores).max()

0.39437317860876375

In [22]:
np.array(precision_scores).max()

0.30632223925823776

In [23]:
np.array(recall_scores).max()

0.5534638554216867

In [26]:
classifier

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [27]:
import pickle 

In [29]:
pickle_rf = open("model_RF.pickle","wb")
pickle.dump(classifier, pickle_rf)
pickle_rf.close()

In [30]:
test_data

[array([0.31545243, 0.48988238, 0.25199717, ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0